version: '3'
services:
  es01:
    image: tf_searchguard_es_kb:esConfigEnvVarSG
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
     #- discovery.seed_hosts=es02,es03
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - safeguard.disabled=false
    ports:
      - 9200:9200
      - 5601:5601
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    tty: true